export const testData = [
  {
    id: 1,
    number: '101',
    type: 'rrrr',
    status: 'unknown',
    sponsor: 'Rafa',
    isFavourite: true,
  },
  {
    id: 2,
    number: '102',
    type: 'vvvv',
    status: 'known',
    sponsor: 'Roger',
    isFavourite: false,
  },
  {
    id: 3,
    number: '103',
    type: 'bbbb',
    status: 'unknown',
    sponsor: 'Nole',
    isFavourite: false,
  },
  {
    id: 4,
    number: '104',
    type: 'nnnn',
    status: 'known',
    sponsor: 'Tommy',
    isFavourite: true,
  },
  {
    id: 5,
    number: '105',
    type: 'qqqq',
    status: 'known',
    sponsor: 'Stan',
    isFavourite: false,
  },
  {
    id: 6,
    number: '106',
    type: 'oooo',
    status: 'unknown',
    sponsor: 'Jannick',
    isFavourite: true,
  },
  {
    id: 7,
    number: '107',
    type: 'eeee',
    status: 'known',
    sponsor: 'XXX',
    isFavourite: false,
  },
  {
    id: 8,
    number: '108',
    type: 'tttt',
    status: 'unknown',
    sponsor: 'YYY',
    isFavourite: true,
  },
];
